name: S3 Deployment
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Upload frontend/public/ To S3
       uses: tpaschalis/s3-sync-action@master
       with:
         args: --acl public-read
       env:
         FILE: ./gh-actions-golang
         AWS_REGION: 'eu-central-1'
         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
